### ISSUE TITLE
File names with ~

### ISSUE THREAD

**Issue by apmoore1** [ltgoslo/norec_fine#1]
Hi,

I have noticed that in the train and dev folders there are a few file names that contain ~ at the end of them, of which these file names are identical to other file names without ~, below is an example of this in the train folder:
100122.ann~
100122.ann

I have never used BRAT before so I am not sure if this is a BRAT output that should exist or if one of the files is an older file? From what I can tell from looking at the files the file name without ~ is more up to date than the file with ~.

Thanks for creating this great resource.

**Comment by apmoore1** [comment]
That issue rendered badly in markdown here is what I wrote with the markdown rendered properly:

I have noticed that in the train and dev folders there are a few file names that contain ~ at the end of them, of which these file names are identical to other file names without ~ , below is an example of this in the train folder:
100122.ann~
100122.ann

I have never used BRAT before so I am not sure if this is a BRAT output that should exist or if one of the files is an older file? From what I can tell from looking at the files the file name without ~ is more up to date than the file with ~.

Thanks for creating this great resource.

**Comment by jerbarnes** [comment]
Hi Andrew,

Those are probably just old backup files that were accidentally uploaded. We're going to release more data soon, so we'll take care of of then. Thanks for the heads up though!

**Comment by jerbarnes** [comment]
We're also adding scripts to convert from BRAT format to Json and Conll formats, which should be up and running soon.

**Comment by jerbarnes** [comment]
Ok, removed the backup files. Thanks again!
