### ISSUE TITLE
NOT annotation

### ISSUE THREAD

**Issue by apmoore1** [ltgoslo/norec_fine#2]
Hi,

I was looking through the dataset and I came across this in training file 700338:
```
T39	Entity 2304 2313;2326 2339	Pi Patels oppfinnsomhet
T40	Polar_expression 2343 2354	imponerende
E13	Polar_expression:T40 Target:T39
A55	Polarity E13 Positive
A56	Source_is_author E13
A57	Intensity E13 Standard
A58	Type E13 E
T41	Polar_expression 2314 2325	utrettelige
E14	Polar_expression:T41 Target:T39
A59	Polarity E14 Positive
A60	Source_is_author E14
A61	Intensity E14 Strong
A62	NOT E14
A63	Type E14 E
```
Which can be found here:
https://github.com/ltgoslo/norec_fine/blob/master/data/train/700338_curation.ann#L111

And I was wondering if the polarity expression holds the NOT annotation and two polarity expressions apply to the same target (as is the case here) and one polarity expression is NOT and the other is not NOT (as is the case here) is the target these two sentiment expressions relate to NOT or not NOT? I'm guessing here that you use the sentiment expression annotation that is the strongest towards the related target. In this case the strongest sentiment is T41 as the intensity is Strong compared to T40 where the intensity is standard. Thus in this case the target would be NOT?

Below is also the JSON format for this annotation taken from your `convert_to_json.py` script:
``` python
{'sent_id': '700338-09-05', 
'text': 'Pi Patels utrettelige oppfinnsomhet er imponerende .', 
'opinions': [
{'Source': [], 
'Target': [['Pi Patels', 'oppfinnsomhet'], ['0:9', '22:35']], 
'Polar_expression': [['imponerende'], ['39:50']], 
'Polarity': 'Positive', 
'Intensity': 'Standard', 
'NOT': False, 
'Source_is_author': True, 
'Target_is_general': False, 
'Type': 'E'}, 
{'Source': [],
 'Target': [['Pi Patels', 'oppfinnsomhet'], ['0:9', '22:35']], 
'Polar_expression': [['utrettelige'], ['10:21']], 
'Polarity': 'Positive', 
'Intensity': 'Strong', 
'NOT': True, 
'Source_is_author': True,
 'Target_is_general': False, 
'Type': 'E'}]}
```
Best,
Andrew.

**Comment by jerbarnes** [comment]
A bit late on our part, but thanks for pointing this out. We were adding more annotations, so we wanted to wait to get everything done before addressing the issue. We've now gone through the all the dataset and fixed the problems we found with conflicting NOT annotations.
