### ISSUE TITLE
Character offset problems

### ISSUE THREAD

**Issue by jerbarnes** [ltgoslo/norec_fine#3]
There are some character offsets which don't seem correct. I made a script to check the offsets versus the tokenization offsets and the results below show the id (document:paragraph:sentence), beginning character offset for the sentence, and the text for each. There will also be some noise because of tokenization, so not every example below is necessarily a mistake.

It would be nice if we could clean this up before I rerun the convert_to_json.py script and remove the original BRAT annotations from the repo.

TRAIN:

101277-05-04 : 17 : orsiktig amatøraften
110965-06-02 : 21 : angt mer spiselig enn « Venn »
202601-09-01 : 8 : skjermen
101115-04-01 : 28 : VG
101115-11-02 : 22 : Langt mer trygg og sol
301338-04-01 : 1 : idelsespornografi
702152-08-02 : 26 : kommer å talefot med yngstemann
001965-06-02 : 277 : latterleg høge talet på referansar til fyll og dop
300040-11-01 : 1 : Potetene
300040-14-01 : 1 : Der gikk du ikke glipp av noe
101419-12-03 : 96 : respekt for Boken med stor B
602087-26-01 : 6 : r ingen sauser som hadde løftet råvarene
705034-09-03 : 32 : Quart 2005
200183-21-03 : 63 : ungerer nå i henhold til Atkinsons syklus
102338-03-02 : 76 : efinere sin egen sjanger
400835-15-04 : 58 : fin i fast inni
202124-02-01 : 113 : Selphy-skrive
202124-18-02 : 94 : kan ikke fungere uten kamera eller PC / Mac
202607-13-05 : 5 : r 2,4-literen
110622-09-01 : 56 : or gamle venner å regne
200520-08-01 : 1 : kke noe råskinn-spesifikasjoner her
002051-07-03 : 12 : Lostprophets
302087-17-01 : 33 : v
109173-09-03 : 5 : ykkes en god stund
301323-07-01 : 21 : Flere steder minner l om stadionrockveien Arcade Fire har tatt
705080-08-02 : 1 : en det viktigste var at den ble holdt
703281-03-01 : 132 : kan lett beskyldes for å prøve seg på en variant av krimsuksessen Jussi Adler-Olsen og historiene om avdeling Q
302850-04-01 : 1 : Wow , dette var da veldig bra !
302850-15-01 : 1 : Matmessig
301212-04-02 : 44 : berømmer ompromissløse mangel på publikumsfrieri
703816-02-09 : 4 : renger noen slike avstikkere for ikke å bli forutsigelige
300016-12-01 : 1 : Se så lekre !
103580-04-04 : 87 : « The Beat Goes on » i
300474-08-01 : 67 : Tross uttallige gjennomlyttinger minimalt som fester seg e
304814-09-01 : 150 : AC / DC
102095-02-01 : 36 : bedre enn noen gan
004068-05-01 : 99 : itt for lite eventyrfølelse ?
004068-16-01 : 60 : kunne gjerne vært litt slemmer
003619-19-01 : 15 : v
109371-10-01 : 23 : r Ørstaviks univers
001922-09-03 : 140 : " I'm Wrong " f
304562-05-03 : 69 : øftes helt klart av å ha så sterke hinderløpere

DEV

300002-04-02 : 208 : Y.M.D
400215-15-02 : 1 : end i tide – det er ingen skam å snu
500716-09-07 : 5 : eny Gaassand Folgerø
400620-18-01 : 34 : he Chronic
704010-03-02 : 35 : kke overbevist hadde klart å gjenta suksessen
705105-04-05 : 166 : første mellomspillet i første sats s

TEST

000787-03-01 : 12 : 80- og 90-tallet d
501595-13-03 : 23 : od opplevelse
201344-19-02 : 137 : Bluetooth 4.0 LE

**Comment by Tyriflis** [comment]
These have now been registered and will be fixed in the coming update. Several of the errors are due to tokenization problems in the original files, where several periods (.) and citation dashes (-) that have not been properly separated from neighbouring tokens have been annotated as being separate, but since sub-token annotation is not allowed, these have been changed to include the punctuation as part of the token. For example,  "Matmessig" in "302850-15-01, mentioned above, should be "-Matmessig", with the dash as part of the token.
