### ISSUE TITLE
Target is general

### ISSUE THREAD

**Issue by apmoore1** [ltgoslo/norec_fine#6]
Hi,

The target is general property appears to be a property of the opinion rather than the target. I have found a case (shown below) where a target has multiple opinions (T33	Entity 547 553	matbar) of which one of the opinions states the target is general to be True where as the other two opinions do not have a target is general property. I may be interpreting this incorrectly and if so apologies in advance. I was wondering which target is general label should I use for the target (T33	Entity 547 553	matbar) as only one of the opinions says True and the other two do not have a label, I assume that the target is general to be True in this case as one of the opinions states this where as the other two do not have a label for target is general. 

This is from the training dataset file `300016`
```
T30	Polar_expression 464 480;527 539	Meccas stilbrudd er erstattet
E5	Polar_expression:T30 Target:T33
A21	Polarity E5 Positive
A22	Source_is_author E5
A23	Intensity E5 Standard
A24	Type E5 E
T31	Polar_expression 558 585	åpner seg opp for Akerselva
E6	Polar_expression:T31 Target:T33
T32	Polar_expression 588 631	ikke stenger for en av byens beste utsikter
E7	Polar_expression:T32 Target:T33
A25	Polarity E7 Positive
A26	Source_is_author E7
A27	Intensity E7 Standard
A28	Target_is_general E7
A29	Type E7 E
T33	Entity 547 553	matbar
```

**Comment by jerbarnes** [comment]
There are a number of these, which I'm adding here:

train

001756-03-02 : " Miami 2 Ibiza ": Conflicting Target_is_general annotations
001756-05-03 : rapperen: Conflicting Target_is_general annotations
107077-17-02 : de forskjellige krigerne og hvilke egenskaper de har: Conflicting Target_is_general annotations
100866-10-01 : Kristina Solums oversettelse: Conflicting Target_is_general annotations
003523-11-01 : : Conflicting Target_is_general annotations
110965-01-02 : « Venn »: Conflicting Target_is_general annotations
202601-02-01 : Bada-mobilen: Conflicting Target_is_general annotations
202601-31-04 : : Conflicting Target_is_general annotations
101882-02-02 : : Conflicting Target_is_general annotations
107972-04-05 : Hun: Conflicting Target_is_general annotations
001965-02-01 : Death By Unga Bungas andrealbum: Conflicting Target_is_general annotations
600117-07-04 : dette: Conflicting Target_is_general annotations
101419-13-03 : papirbokens: Conflicting Target_is_general annotations
703152-03-02 : : Conflicting Target_is_general annotations
701606-03-06 : « The moment after »: Conflicting Target_is_general annotations
602087-19-02 : : Conflicting Target_is_general annotations
705034-08-03 : : Conflicting Target_is_general annotations
001521-05-02 : takning på hardcore: Conflicting Target_is_general annotations
100831-04-03 : « Jookbox Charade »: Conflicting Target_is_general annotations
704907-06-04 : konsertopplevelse: Conflicting Target_is_general annotations
702788-06-05 : film: Conflicting Target_is_general annotations
100122-04-02 : : Conflicting Target_is_general annotations
106155-11-01 : spillet: Conflicting Target_is_general annotations
106155-13-01 : « Tiberium Wars »: Conflicting Target_is_general annotations
201174-17-02 : 3K: Conflicting Target_is_general annotations
001349-04-04 : The Pink Robots: Conflicting Target_is_general annotations
110371-03-03 : Filmen: Conflicting Target_is_general annotations
106360-11-03 : « Twilight Princess »: Conflicting Target_is_general annotations
000076-05-01 : eventyret: Conflicting Target_is_general annotations
109566-05-02 : DeGraw: Conflicting Target_is_general annotations
300016-05-01 : : Conflicting Target_is_general annotations
300016-05-02 : matbar: Conflicting Target_is_general annotations
300016-18-01 : Elvebredden: Conflicting Target_is_general annotations
300178-12-01 : teateroppsetning: Conflicting Target_is_general annotations
202043-24-01 : den: Conflicting Target_is_general annotations
004068-05-01 : film: Conflicting Target_is_general annotations
103635-04-01 : artist: Conflicting Target_is_general annotations
003619-20-03 : The A-Team: Conflicting Target_is_general annotations
001922-04-02 : : Conflicting Target_is_general annotations
102687-07-02 : : Conflicting Target_is_general annotations
109778-13-02 : serien: Conflicting Target_is_general annotations
200247-02-02 : spillet: Conflicting Target_is_general annotations
200247-20-04 : spillet: Conflicting Target_is_general annotations

dev

300002-04-02 : « Can I Feel »: Conflicting Target_is_general annotations
400215-05-02 : : Conflicting Target_is_general annotations
601625-02-03 : plate: Conflicting Target_is_general annotations
500718-09-05 : stykket: Conflicting Target_is_general annotations
501135-05-01 : : Conflicting Target_is_general annotations
105373-06-01 : In Flames: Conflicting Target_is_general annotations
105373-09-01 : : Conflicting Target_is_general annotations
000335-15-01 : : Conflicting Target_is_general annotations
400620-18-04 : : Conflicting Target_is_general annotations
303164-06-02 : album: Conflicting Target_is_general annotations
400109-11-02 : : Conflicting Target_is_general annotations
400109-12-01 : A Monster Calls: Conflicting Target_is_general annotations
202263-18-02 : : Conflicting Target_is_general annotations

test

704794-02-01 : : Conflicting Target_is_general annotations
400175-02-01 : krigsfilm: Conflicting Target_is_general annotations
300186-04-02 : tilhengerskare: Conflicting Target_is_general annotations
500201-03-02 : Jayro Bustamante: Conflicting Target_is_general annotations
000913-27-01 : Dishonored 2: Conflicting Target_is_general annotations
302108-09-02 : : Conflicting Target_is_general annotations
304926-06-02 : : Conflicting Target_is_general annotations
002988-06-05 : « Attitudeproblem »: Conflicting Target_is_general annotations

**Comment by Tyriflis** [comment]
All but one of the cases where two polar expressions share the same target have been incorrectly annotated. The exception is the following:

100866-10-01 : Kristina Solums oversettelse: Conflicting Target_is_general annotations

In this case, the different polar expressions evoke two different interpretation of the target: the quality of the translation, and the product of the translation, where only the latter is seen as general in this case.

The ones where the target is empty are implicit polar expressions. It is more common for these to have conflicting Target_is_general annotations as they do not necessarily share their implicit targets. Some errors have still slipped through, and will be corrected in the next version.

The cases that do **not** contain errors are the following:

train

001922-04-02 : : Conflicting Target_is_general annotations
202601-31-04 : : Conflicting Target_is_general annotations
300016-05-01 : : Conflicting Target_is_general annotations
102687-07-02 : : Conflicting Target_is_general annotations
003523-11-01 : : Conflicting Target_is_general annotations

dev

000335-15-01 : : Conflicting Target_is_general annotations
202263-18-02 : : Conflicting Target_is_general annotations
400620-18-04 : : Conflicting Target_is_general annotations
400215-05-02 : : Conflicting Target_is_general annotations
105373-09-01 : : Conflicting Target_is_general annotations
501135-05-01 : : Conflicting Target_is_general annotations
400109-11-02 : : Conflicting Target_is_general annotations

test

302108-09-02 : : Conflicting Target_is_general annotations
304926-06-02 : : Conflicting Target_is_general annotations

**Comment by Tyriflis** [comment]
The test has also been performed for the coming additions to the corpus. The following sentences do not contain errors:

The sentences are all from the train split:

200323-42-01 : : Conflicting Target_is_general annotations
200140-13-02 : Den: Conflicting Target_is_general annotations
109725-03-01 : : Conflicting Target_is_general annotations
105165-02-04 : : Conflicting Target_is_general annotations
201835-23-08 : : Conflicting Target_is_general annotations
110844-04-01 : : Conflicting Target_is_general annotations
